name: dart_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_messaging: ^16.0.2
  firebase_storage: ^13.0.2
  cloud_functions: ^6.0.2
  flutter_riverpod: ^3.0.1
  riverpod_annotation: ^3.0.1
  freezed_annotation: ^3.1.0
  flutter_chat_ui: ^2.9.0
  image_picker: ^1.2.0
  uuid: ^4.5.1
  google_fonts: ^6.3.2
  flex_color_scheme: ^8.3.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.1
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
