name: dart_chat
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  chatview: ^2.4.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  flex_color_scheme: ^8.0.1
  flutter:
    sdk: flutter
  flutter_neumorphic_plus: ^3.4.0
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
